### ISSUE TITLE
Knight & Blackguard Smite Issues

### ISSUE THREAD

**Issue by Zarakul** [edmaster44/SigilUpdate#3]
If these new Smites are meant to be a melee-only feature, the range needs to be dropped down per the comment's claim.
https://github.com/Mimi-Techmouse/SigilUpdate/blob/f939a88a0b9f18b797c05066bec977d0f9aa3e20/scod_a_knightsmite_inc.NSS#L11
https://github.com/Mimi-Techmouse/SigilUpdate/blob/f939a88a0b9f18b797c05066bec977d0f9aa3e20/scod_a_blackguardsmite_inc.NSS#L14

Where Blackguard checks for the target's alignment and only seeks 'Good,' Knight does not seem to check for any alignment at all. If this is the case, please confirm so that I can update the wiki's entry on 'Smite Infidel (Knight)'

**Comment by Glyth** [comment]
Fixed in rev a94c496
